### ISSUE TITLE
Load Scene button is disabled even with valid Mesh/PLY filepaths in OrbitNavImporter extension

### ISSUE THREAD

**Issue by dillonloh** [pascal-roth/orbit_envs#1]
### Summary
The `Load Scene` button in the UI for Orbit Nav Importer extension is grayed out and unable to be used. This happens even if I load valid filepaths for the Mesh and PLY fields. However, `Reset Scene` button works fine.

### Steps to reproduce
Environment: IsaacSim v4.2.0
Running on dev/add_sampling branch of this repo.
Install orbit (IsaacLab) v0.3.0 as per README and follow all steps to setup

Open IsaacSim, enable the Orbit Nav Importer extension, and attempt to use the UI. No matter how I changed the filepaths and toggled with the options, the `Load Scene` button remained grey.

### Possible Source of Bug
In the file `extensions/orbit.nav.importer/orbit/nav/importer/scripts/importer_ext.py`, lines 345 and 349 have defined the `load_btn` input field to be disabled (refer to ss). 

**If i change it to True, the load button works fine, and the rest of the functionality involved in loading in the Matterport environment works with no issue.**

![image](https://github.com/user-attachments/assets/635182c7-69a4-4f8f-b3e8-6d9dafcac331)

### What is the current _bug_ behavior?
`Load Scene` button is disabled

### What is the expected _correct_ behavior?
`Load Scene` button should be enabled (maybe with conditions like valid filepaths provided etc.)

### Relevant logs and/or screenshots

![image](https://github.com/user-attachments/assets/9ef2b009-b507-447f-b498-7c78fec913ea)

**Comment by dillonloh** [comment]
just a tiny issue, not sure if its intended behaviour but it was blocking usage on my side so i just wanted to bring it up.
thanks for creating this project!

**Comment by pascal-roth** [comment]
Hi @dillonloh, 

thanks a lot for using our work. The repo here is not really maintained anymore, please use https://github.com/leggedrobotics/viplanner/pull/32 (or the main branch as soon as the PR is merged)
