### ISSUE TITLE
Add Camera via Matterport Extension: TypeError: PinholeCameraPatternCfg.__init__() got an unexpected keyword argument 'data_types'

### ISSUE THREAD

**Issue by dillonloh** [pascal-roth/orbit_envs#2]
### Summary
After importing a usd file via the Matterport extension, if we try to add a camera using the UI, we get the following error:
```
2024-10-20 15:35:54 [200,816ms] [Error] [omni.ui.python] TypeError: PinholeCameraPatternCfg.__init__() got an unexpected keyword argument 'data_types'

At:
  /home/dillon/IsaacLab/source/extensions/omni.isaac.matterport/omni/isaac/matterport/scripts/matterport_ext.py(445): _register_camera

```
![image](https://github.com/user-attachments/assets/5a6df69d-e8b7-428e-bbaf-ab83ce3be0a8)

![image](https://github.com/user-attachments/assets/9684d810-13b5-4427-beec-b833cdaad1eb)

### Possible Cause
In `extensions/omni.isaac.matterport/omni/isaac/matterport/scripts/matterport_ext.py`, lines 445 - 450, `data_types` arg is provided to the `patterns.PinholeCameraPatternCfg` class. However, according to > v0.3.0 documentation for orbit, this class does not take this parameter.

![image](https://github.com/user-attachments/assets/21af1bf7-37cf-4e95-a833-fae1489b102a)

### Possible Fixes

It is difficult for me to understand the MatterportDomains class, so I cannot be sure, but it seems natural that the `data_types` should be provided to the `RayCasterCameraCfg` class instead. However, I do not see this class being instantiated. Related to this matter, I do not understand why the camera_cfg defined in line 452 is an instance of `RayCasterCfg`, especially since inside `MatterportDomains.register_camera()`, camera_cfg is treated as both an instance of RayCasterCfg and RayCasterCameraCfg.
I have tried replacing RayCasterCfg with RayCasterCameraCfg in lines 452-459, but IsaacSim crashes with minimal logging when I try to add a camera afterwards.

### Question
Would greatly appreciate if you could clarify if the data_types parameter should be passed in a different place then where it is now please.

**Comment by pascal-roth** [comment]
Hi @dillonloh 

thanks for noticing the error. The GUI is not really maintained anymore. Please use https://github.com/leggedrobotics/viplanner/pull/32 (or the main as soon as it is merged) for the latest version. We are currently working on a fix for the UI
